# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from stt_async import stt_async_service_pb2 as stt__async_dot_stt__async__service__pb2
from yandex.cloud.operation import operation_pb2 as yandex_dot_cloud_dot_operation_dot_operation__pb2


class AsyncRecognizerStub(object):
    """A set of methods for async voice recognition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeFile = channel.unary_unary(
                '/speechkit.stt_async.AsyncRecognizer/RecognizeFile',
                request_serializer=stt__async_dot_stt__async__service__pb2.RecognizeFileRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.RecognizeFileStreaming = channel.stream_unary(
                '/speechkit.stt_async.AsyncRecognizer/RecognizeFileStreaming',
                request_serializer=stt__async_dot_stt__async__service__pb2.RecognizeFileStreamingRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.GetRecognition = channel.unary_stream(
                '/speechkit.stt_async.AsyncRecognizer/GetRecognition',
                request_serializer=stt__async_dot_stt__async__service__pb2.GetRecognitionRequest.SerializeToString,
                response_deserializer=stt__async_dot_stt__async__service__pb2.StreamingResponse.FromString,
                )
        self.GetProgress = channel.unary_unary(
                '/speechkit.stt_async.AsyncRecognizer/GetProgress',
                request_serializer=stt__async_dot_stt__async__service__pb2.GetProgressRequest.SerializeToString,
                response_deserializer=stt__async_dot_stt__async__service__pb2.ProgressResponse.FromString,
                )
        self.DeleteRecognition = channel.unary_unary(
                '/speechkit.stt_async.AsyncRecognizer/DeleteRecognition',
                request_serializer=stt__async_dot_stt__async__service__pb2.DeleteRecognitionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AsyncRecognizerServicer(object):
    """A set of methods for async voice recognition.
    """

    def RecognizeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFileStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecognition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecognition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncRecognizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFile,
                    request_deserializer=stt__async_dot_stt__async__service__pb2.RecognizeFileRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'RecognizeFileStreaming': grpc.stream_unary_rpc_method_handler(
                    servicer.RecognizeFileStreaming,
                    request_deserializer=stt__async_dot_stt__async__service__pb2.RecognizeFileStreamingRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'GetRecognition': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRecognition,
                    request_deserializer=stt__async_dot_stt__async__service__pb2.GetRecognitionRequest.FromString,
                    response_serializer=stt__async_dot_stt__async__service__pb2.StreamingResponse.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=stt__async_dot_stt__async__service__pb2.GetProgressRequest.FromString,
                    response_serializer=stt__async_dot_stt__async__service__pb2.ProgressResponse.SerializeToString,
            ),
            'DeleteRecognition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecognition,
                    request_deserializer=stt__async_dot_stt__async__service__pb2.DeleteRecognitionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speechkit.stt_async.AsyncRecognizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsyncRecognizer(object):
    """A set of methods for async voice recognition.
    """

    @staticmethod
    def RecognizeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.stt_async.AsyncRecognizer/RecognizeFile',
            stt__async_dot_stt__async__service__pb2.RecognizeFileRequest.SerializeToString,
            yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeFileStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/speechkit.stt_async.AsyncRecognizer/RecognizeFileStreaming',
            stt__async_dot_stt__async__service__pb2.RecognizeFileStreamingRequest.SerializeToString,
            yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/speechkit.stt_async.AsyncRecognizer/GetRecognition',
            stt__async_dot_stt__async__service__pb2.GetRecognitionRequest.SerializeToString,
            stt__async_dot_stt__async__service__pb2.StreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.stt_async.AsyncRecognizer/GetProgress',
            stt__async_dot_stt__async__service__pb2.GetProgressRequest.SerializeToString,
            stt__async_dot_stt__async__service__pb2.ProgressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.stt_async.AsyncRecognizer/DeleteRecognition',
            stt__async_dot_stt__async__service__pb2.DeleteRecognitionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
