# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lang_detect import lang_detect_service_pb2 as lang__detect_dot_lang__detect__service__pb2


class LangDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFromAudio = channel.unary_unary(
                '/speechkit.lang_detect.LangDetector/DetectFromAudio',
                request_serializer=lang__detect_dot_lang__detect__service__pb2.AudioLangDetectRequest.SerializeToString,
                response_deserializer=lang__detect_dot_lang__detect__service__pb2.LangDetectResponse.FromString,
                )


class LangDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectFromAudio(self, request, context):
        """Synchronous audio language detection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFromAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFromAudio,
                    request_deserializer=lang__detect_dot_lang__detect__service__pb2.AudioLangDetectRequest.FromString,
                    response_serializer=lang__detect_dot_lang__detect__service__pb2.LangDetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speechkit.lang_detect.LangDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LangDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectFromAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.lang_detect.LangDetector/DetectFromAudio',
            lang__detect_dot_lang__detect__service__pb2.AudioLangDetectRequest.SerializeToString,
            lang__detect_dot_lang__detect__service__pb2.LangDetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
