# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lang_detect/lang_detect_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%lang_detect/lang_detect_service.proto\x12\x15speechkit.lang_detect\x1a\x1cgoogle/api/annotations.proto\"G\n\x16\x41udioLangDetectRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x19\n\x11\x61llowed_languages\x18\x02 \x03(\t\"\x94\x01\n\x12LangDetectResponse\x12\x18\n\x10\x61llowed_language\x18\x01 \x01(\t\x12#\n\x1b\x61llowed_language_confidence\x18\x02 \x01(\x02\x12\x19\n\x11\x64\x65tected_language\x18\x03 \x01(\t\x12$\n\x1c\x64\x65tected_language_confidence\x18\x04 \x01(\x02\x32\x96\x01\n\x0cLangDetector\x12\x85\x01\n\x0f\x44\x65tectFromAudio\x12-.speechkit.lang_detect.AudioLangDetectRequest\x1a).speechkit.lang_detect.LangDetectResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/detectFromAudiob\x06proto3')



_AUDIOLANGDETECTREQUEST = DESCRIPTOR.message_types_by_name['AudioLangDetectRequest']
_LANGDETECTRESPONSE = DESCRIPTOR.message_types_by_name['LangDetectResponse']
AudioLangDetectRequest = _reflection.GeneratedProtocolMessageType('AudioLangDetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOLANGDETECTREQUEST,
  '__module__' : 'lang_detect.lang_detect_service_pb2'
  # @@protoc_insertion_point(class_scope:speechkit.lang_detect.AudioLangDetectRequest)
  })
_sym_db.RegisterMessage(AudioLangDetectRequest)

LangDetectResponse = _reflection.GeneratedProtocolMessageType('LangDetectResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANGDETECTRESPONSE,
  '__module__' : 'lang_detect.lang_detect_service_pb2'
  # @@protoc_insertion_point(class_scope:speechkit.lang_detect.LangDetectResponse)
  })
_sym_db.RegisterMessage(LangDetectResponse)

_LANGDETECTOR = DESCRIPTOR.services_by_name['LangDetector']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANGDETECTOR.methods_by_name['DetectFromAudio']._options = None
  _LANGDETECTOR.methods_by_name['DetectFromAudio']._serialized_options = b'\202\323\344\223\002\022\"\020/detectFromAudio'
  _AUDIOLANGDETECTREQUEST._serialized_start=94
  _AUDIOLANGDETECTREQUEST._serialized_end=165
  _LANGDETECTRESPONSE._serialized_start=168
  _LANGDETECTRESPONSE._serialized_end=316
  _LANGDETECTOR._serialized_start=319
  _LANGDETECTOR._serialized_end=469
# @@protoc_insertion_point(module_scope)
