# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from postprocess_asr import postprocess_asr_service_pb2 as postprocess__asr_dot_postprocess__asr__service__pb2
from yandex.cloud.operation import operation_pb2 as yandex_dot_cloud_dot_operation_dot_operation__pb2


class AsyncAsrPostprocessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostprocessAsr = channel.unary_unary(
                '/speechkit.postprocess_asr.AsyncAsrPostprocessor/PostprocessAsr',
                request_serializer=postprocess__asr_dot_postprocess__asr__service__pb2.PostprocessAsrRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.GetRecognition = channel.unary_unary(
                '/speechkit.postprocess_asr.AsyncAsrPostprocessor/GetRecognition',
                request_serializer=postprocess__asr_dot_postprocess__asr__service__pb2.GetRecognitionRequest.SerializeToString,
                response_deserializer=postprocess__asr_dot_postprocess__asr__service__pb2.PostprocessAsrResponse.FromString,
                )
        self.GetProgress = channel.unary_unary(
                '/speechkit.postprocess_asr.AsyncAsrPostprocessor/GetProgress',
                request_serializer=postprocess__asr_dot_postprocess__asr__service__pb2.GetProgressRequest.SerializeToString,
                response_deserializer=postprocess__asr_dot_postprocess__asr__service__pb2.ProgressResponse.FromString,
                )
        self.DeleteRecognition = channel.unary_unary(
                '/speechkit.postprocess_asr.AsyncAsrPostprocessor/DeleteRecognition',
                request_serializer=postprocess__asr_dot_postprocess__asr__service__pb2.DeleteRecognitionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AsyncAsrPostprocessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostprocessAsr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecognition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecognition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncAsrPostprocessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostprocessAsr': grpc.unary_unary_rpc_method_handler(
                    servicer.PostprocessAsr,
                    request_deserializer=postprocess__asr_dot_postprocess__asr__service__pb2.PostprocessAsrRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'GetRecognition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecognition,
                    request_deserializer=postprocess__asr_dot_postprocess__asr__service__pb2.GetRecognitionRequest.FromString,
                    response_serializer=postprocess__asr_dot_postprocess__asr__service__pb2.PostprocessAsrResponse.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=postprocess__asr_dot_postprocess__asr__service__pb2.GetProgressRequest.FromString,
                    response_serializer=postprocess__asr_dot_postprocess__asr__service__pb2.ProgressResponse.SerializeToString,
            ),
            'DeleteRecognition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecognition,
                    request_deserializer=postprocess__asr_dot_postprocess__asr__service__pb2.DeleteRecognitionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speechkit.postprocess_asr.AsyncAsrPostprocessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsyncAsrPostprocessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostprocessAsr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.postprocess_asr.AsyncAsrPostprocessor/PostprocessAsr',
            postprocess__asr_dot_postprocess__asr__service__pb2.PostprocessAsrRequest.SerializeToString,
            yandex_dot_cloud_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.postprocess_asr.AsyncAsrPostprocessor/GetRecognition',
            postprocess__asr_dot_postprocess__asr__service__pb2.GetRecognitionRequest.SerializeToString,
            postprocess__asr_dot_postprocess__asr__service__pb2.PostprocessAsrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.postprocess_asr.AsyncAsrPostprocessor/GetProgress',
            postprocess__asr_dot_postprocess__asr__service__pb2.GetProgressRequest.SerializeToString,
            postprocess__asr_dot_postprocess__asr__service__pb2.ProgressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/speechkit.postprocess_asr.AsyncAsrPostprocessor/DeleteRecognition',
            postprocess__asr_dot_postprocess__asr__service__pb2.DeleteRecognitionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
